@extends('layout.app')
@section('title', 'Sentinel')
@section('content')
	
	<section id="hero">
		<div class="hero-container" data-aos="fade-in">
			<h1><span>S</span>entinel</h1>
			<h2>Multi Language AI content Detector</h2>
			<!-- form -->
			<div>
				<form method="POST" class="form">
					<!-- text area -->
					<div class="form-group">
						<textarea class="form-control vw-80" id="content" name="content" rows="10" 
							placeholder="paste in the content you want to analyze" minlength="250" required></textarea>
					</div>


					<div class="row mt-3">
						<!-- input file -->
						<div class="col-md-6 col-sm-12">
							<div class="form-group mt-3">
								<!--input type="file" class="form-control" id="document" name="document" placeholder="or Choose a file" /-->
								<input type="file" class="form-control" id="document" name="document" placeholder="or Choose a file" accept=".txt,.doc,.docx,.pdf,image/*">
							</div>							
						</div>

						<div class="col-md-6 col-sm-12">
							<div class="form-group mt-3 text-end">
								<button type="submit" id="analyze" class="btn btn-primary w-50 ">Analyze</button>
							</div>
						</div>
					</div>					

				</form>
			</div>

			<!-- result -->
			<div class="result vw-80 text-start mt-5" id="result">
				
			</div>
		</div>
	</section>

@endsection

@section('script')
<script>

	function finalize_result($prob, $amount){

		// round amount to 2 decimal places
		$amount = $amount.toFixed(2);
		
		if($prob > 0){
			if($amount > 50){
				
				return `<h1 class='text-center text-danger'>The Content is likely generated by AI</h1>
						<p class='text-center text-danger fw-bold'>The content is ${$amount}% generated by AI</p>`;
			} else if($amount > 25){

				return `<h1 class='text-center text-warning'>A substantial amount of the content is likely generated by AI</h1>
						<p class='text-center text-warning fw-bold'>The content is ${$amount}% generated by AI</p>`;
			}else{
				return `<h1 class='text-center text-info'>A small portion of the content is likely generated by AI</h1>
						<p class='text-center text-info fw-bold'>The content is ${$amount}% generated by AI</p>`;
			}
		} else{
			return "<h1 class='text-center text-success'>The Content is likely Human Written</h1>";
		}
	}

	function process_request(document){

		$.ajax({
			url: '/api/v1/analyze',
			type: 'POST',
			data: { document: document },
			success: function(response){
				/*  Example response
					{
						"documents": [{ "average_generated_prob": 0, "completely_generated_prob": 0.0002586307527963072, "overall_burstiness": 0,
							"paragraphs": [{ "completely_generated_prob": 0.11111110864197533, "num_sentences": 1, "start_sentence_index": 0 }],
							"sentences": [ { "generated_prob": 0, "perplexity": 5328, "sentence": "hello world" }, "...", "..." ]
						}]
					}

					Error response
					{
						"error": "You have exceeded your usage threshold of 7 requests per hour. Please try again later"
					}
				*/



				// if error
				if(response.error){
					swal("Sorry!", "You have exceeded your usage threshold of 7 requests per hour. Please try again later", "error").then(function(){
						$('#analyze').attr('disabled', false);
						$('#analyze').html('Analyze');
					});
					return false;
				}

				try
				{
					// replace the result with the refined result
					var average_generated_prob = response.documents[0].average_generated_prob;
					var completely_generated_prob = response.documents[0].completely_generated_prob * 100;

					// TOD: we'll add a pie chart to indicate the percentage of the generated content
					
					// process result from finalize_result function and display it
					var result = finalize_result(average_generated_prob, completely_generated_prob);
					$('#result').html(result);
				}
				catch(err)
				{
					swal("Sorry!", "Unknown error occured", "error").then(function(){
						$('#analyze').attr('disabled', false);
						$('#analyze').html('Analyze');
					});
				}

			}
		}).then(function(){
			// restore button initial state
			$('#analyze').attr('disabled', false);
			$('#analyze').html('Analyze');
		});

	}
	
	$(document).ready(function(){
		// on form submit event
		
		$('.form').submit(function(e){
			
			e.preventDefault();

			// disable the button and is_loading
			$('#analyze').attr('disabled', true);
			$('#analyze').html('<div class="spinner-border" role="status"></div>');
			
			var document = $('#content').val();

			process_request(document);

		});

		// file input change event
		$('#document').change(function(e){
			// disable the button and is_loading
			$('#analyze').attr('disabled', true);
			$('#analyze').html('<div class="spinner-border" role="status"></div>');

			// if file is not txt return false
			if(!e.target.files[0].name.endsWith('.txt')){
				swal("Sorry!", "We now can only process text files!", "error").then(function(){
					$('#analyze').attr('disabled', false);
					$('#analyze').html('Analyze');
				});
				return false;
			}

			// get the file
			var file = e.target.files[0];
			var reader = new FileReader();
			reader.readAsText(file);

			reader.onload = function(e){
				var document = e.target.result;
				process_request(document);
			}
		});


	});
</script>
@endsection